name: Run Codecov
on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"
    strategy:
        matrix:
            python: [3.7, 3.8]
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: {% raw %}${{ matrix.python }}{% endraw %}

    - name: Generate coverage report
      run: |
        pip install -r requirements_dev.txt
        pip install pytest-cov
        pytest --cov-config=.coveragerc --cov={{ cookiecutter.project_slug }}/ --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:

        #TODO COOKIETEMPLE: If your repository is private you are required to set a CODECOV_TOKEN as a secret into your Github repository.
        #See: https://docs.codecov.io/docs/about-the-codecov-bash-uploader#upload-token and
        #https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets.
        #No token is required if your repository is public.

        token: {% raw %}${{ secrets.CODECOV_TOKEN }}{% endraw %}
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
